### ISSUE TITLE
[Feature][Binlog] support Binlog

### ISSUE THREAD

**Issue by huangxianxin** [apache/incubator-seatunnel#952] opened 2022-01-06 02:38 UTC
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

add support of Binlog

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment] 2022-01-06 03:41
SGTM, Can you produce the corresponding design first?

**Comment by huangxianxin** [comment] 2022-01-06 03:56
> 

I give it a try and hope to get suggestions from everyone

**Comment by huangxianxin** [comment] 2022-01-06 04:00
> 

I give it a try and hope to get suggestions from everyone

**Comment by xtr1993** [comment] 2022-01-07 09:48
can you think more
if seatunnel can use binlog then could cdc be used?

https://github.com/apache/incubator-seatunnel/issues/963

**Comment by garyelephant** [comment] 2022-01-08 06:31
duplicate of #963, please discuss this in #963

**Closed by garyelephant** 2022-01-08 06:31 UTC
Labels: discuss
