### ISSUE TITLE
[Feature][Spark] support debezium

### ISSUE THREAD

**Issue by melin** [apache/incubator-seatunnel#946] opened 2022-01-04 05:26 UTC
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Integrated with Debezium to support realtime writing of data to hudi

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xtr1993** [comment] 2022-01-05 09:59
spark how to support debezium？you have done it?

**Comment by melin** [comment] 2022-01-06 01:23
The Flink CDC project uses Debezium Embedded directly to obtain binlog.
Spark can use the output of Debezium Embedded as a streaming data source

xtr_1993 ***@***.***> 于2022年1月5日周三 17:59写道：

**Comment by garyelephant** [comment] 2022-01-08 06:31
duplicate of #963. we can discuss this in #963

**Closed by garyelephant** 2022-01-08 06:31 UTC
Labels: discuss
